<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[application launchedhttps://www.facebook.com/]]>
    </line>
  </reporter-output>
  <suite started-at="2024-10-29T12:23:50 IST" name="Default suite" finished-at="2024-10-29T12:24:09 IST" duration-ms="18310">
    <groups>
    </groups>
    <test started-at="2024-10-29T12:23:50 IST" name="Default test" finished-at="2024-10-29T12:24:09 IST" duration-ms="18310">
      <class name="Test.Userlog_211024">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:Test.Userlog_211024@55141def]" started-at="2024-10-29T12:23:51 IST" name="openApplication" finished-at="2024-10-29T12:23:55 IST" duration-ms="4979" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[application launchedhttps://www.facebook.com/]]>
            </line>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login()[pri:0, instance:Test.Userlog_211024@55141def]" started-at="2024-10-29T12:23:55 IST" name="login" finished-at="2024-10-29T12:24:09 IST" duration-ms="13096" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3],
expected [8] but found [3]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at POM.WelcomePage.fblogin(WelcomePage.java:115)
at Test.Userlog_211024.login(Userlog_211024.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:Test.Userlog_211024@55141def]" started-at="2024-10-29T12:24:09 IST" name="closeApplication" finished-at="2024-10-29T12:24:09 IST" duration-ms="185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- Test.Userlog_211024 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
